Slight profile changes
jcolladokuri/CodeU-Spring-2018 pull request #34
Opened 2018-07-02 19:16 UTC by eselenic

Just adding some tweaks so the About me section will show when edited.

2018-07-02 19:27 UTC, Rafer45 requested changes
A few nitpicks (braces and variables)

2018-07-02 19:27 UTC, Rafer45 commented on src/main/webapp/WEB-INF/view/profile.jsp
>    <% List<Profile> profiles = (List<Profile>) request.getAttribute("profiles");
In line 21, why are we storing the `"username"` attribute, if we already have the `"user"`?

2018-07-02 19:27 UTC, Rafer45 commented on src/main/java/codeu/controller/ProfileServlet.java
> +    {
These braces should be tweaked a little bit, to follow the standard.
So instead of
```
}
else
{
```
just having `} else {`

2018-07-02 19:27 UTC, Rafer45 commented on src/main/webapp/WEB-INF/view/profile.jsp
>        String user = (String) request.getSession().getAttribute("user");
Instead of reassigning this every iteration of the loop, try pulling it outside the loop (maybe at the top, since you use it a couple times).

2018-07-02 19:27 UTC, Rafer45 commented on src/main/java/codeu/model/store/basic/ProfileStore.java
> +  public String getAbout(UUID id){
It would be faster to have an internal map from IDs to Profile objects and using that, but this works well at this scope.

2018-07-09 12:20 UTC, eselenic commented on src/main/java/codeu/model/store/basic/ProfileStore.java
> +  public String getAbout(UUID id){
Noted! I'll look into that for the next pull request

2018-07-09 12:23 UTC, eselenic commented on src/main/webapp/WEB-INF/view/profile.jsp
>    <% List<Profile> profiles = (List<Profile>) request.getAttribute("profiles");
Forgot to delete the line. I structured it differently the last time. Good catch

2018-07-09 12:28 UTC, eselenic commented on src/main/java/codeu/controller/ProfileServlet.java
> +    {
Done

2018-07-09 12:29 UTC, eselenic commented on src/main/webapp/WEB-INF/view/profile.jsp
>        String user = (String) request.getSession().getAttribute("user");
Done

2018-07-09 19:10 UTC, Rafer45 approved these changes
LGTM!

2018-07-12 17:04 UTC, merged